# Generated by Django 3.2.8 on 2021-10-15 00:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('profile_photo', models.ImageField(upload_to=users.models.profile_photo_directory_path, verbose_name='Profile Photo')),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('bio', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
